version: 2.0
jobs:
  build:
    working_directory: /go/src/tickets
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Get packages
          command: |
              go get -u github.com/golang/dep/cmd/dep && \
              /go/bin/dep ensure
      - run:
          name: Build
          command: go build cmd/api.go
      - run:
          name: Test
          command: go test
