version: 2.0
jobs:
  build:
    working_directory: /go/src/tickets
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Get packages
          command: |
              go get github.com/rs/cors && \
              go get github.com/gorilla/mux && \
              go get gopkg.in/mgo.v2 && \
              go get github.com/urfave/negroni && \
              go get github.com/stretchr/testify/assert && \
              go get github.com/thoas/stats
      - run:
          name: Build
          command: go build cmd/api.go
      - run:
          name: Test
          command: go test
