version: 2.0
jobs:
  build:
    working_directory: /go/src/tickets
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Get packages
          command: |
              go get github.com/gorilla/mux && \
              go get github.com/urfave/negroni && \
              go get github.com/stretchr/testify/assert && \
              go get gopkg.in/mgo.v2
      - run:
          name: Build
          command: go build cmd/api/server.go
      - run:
          name: Test
          command: go test
