version: 2.0
jobs:
  build:
    working_directory: /go/src/api
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Get packages
          command: |
              go get github.com/labstack/echo && \
              go get github.com/labstack/echo/middleware && \
              go get github.com/stretchr/testify/assert && \
              go get gopkg.in/mgo.v2
      - run:
          name: Build
          command: go build 
      - run:
          name: Validate
          command: go vet cmd/api/server.go && go test
